# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Construct new FM Index
#'
#' FM indices are data structures for memory efficient storage of large
#' sets of strings. Searches for partial matches of query strings within the
#' set of strings in the index are extremely fast.
#'
#' @param strings Vector of strings to construct FM index from
#' @param case_sensitive Build case-sensitive index if TRUE
#'
#' @examples
#' data("state")
#' index <- fm_index_construct(state.name, case_sensitive = FALSE)
#'
#' @family FM Index functions
#' @export
#' @importFrom stringi stri_trans_tolower
fm_index_construct <- function(strings, case_sensitive = FALSE) {
    .Call(`_fm_index_fm_index_construct`, strings, case_sensitive)
}

#' Find given queries in FM Index
#'
#' @param queries Vector of strings to find in FM index
#' @param index Index created with [fm_index_construct()]
#'
#' @examples
#' data("state")
#' index <- fm_index_construct(state.name, case_sensitive = FALSE)
#' # Find all states with "new" in their names
#' hits <- fm_index_find("new", index)
#' hits
#' # Show matching strings in library
#' state.name[hits$library_index]
#'
#' hits <- fm_index_find("ar", index)
#' hits
#' state.name[hits$library_index]
#'
#' @family FM Index functions
#' @export
fm_index_find <- function(queries, index) {
    .Call(`_fm_index_fm_index_find`, queries, index)
}

#' Save / load FM indices
#'
#' FM indices can be stored on disk and loaded into memory again in order
#' to avoid re-computing the index every time a new R session is opened.
#'
#' @param path Path where to save index to or load index from
#'
#' @examples
#' data("state")
#' index_1 <- fm_index_construct(state.name, case_sensitive = FALSE)
#'
#' tmp_path <- tempfile()
#' fm_index_save(index_1, tmp_path)
#' index_2 <- fm_index_load(tmp_path)
#'
#' identical(
#'   fm_index_find("new", index_1),
#'   fm_index_find("new", index_2)
#' )
#'
#' @describeIn fm_index_save Save FM Index to disk
#' @family FM Index functions
#' @export
fm_index_save <- function(index, path) {
    invisible(.Call(`_fm_index_fm_index_save`, index, path))
}

#' @describeIn fm_index_save Load FM Index from disk
#' @export
fm_index_load <- function(path) {
    .Call(`_fm_index_fm_index_load`, path)
}

