# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Construct FM Index
#'
#' @param strings Vector of strings to construct FM index from
#' @export
construct_fm_index <- function(strings) {
    .Call(`_fm_index_construct_fm_index`, strings)
}

#' Find query in FM Index
#'
#' @param query Strings to find in FM index
#' @param index Pointer to index created with [construct_fm_index()]
#' @export
fm_index_find <- function(query, index) {
    .Call(`_fm_index_fm_index_find`, query, index)
}

