# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' FM Index functions
#'
#' FM indices are data structures for memory efficient storage of large
#' sets of strings. Searches for partial matches of query strings within the
#' set of strings in the index are extremely fast.
#'
#' \itemize{
#' \item \code{fm_index_construct} Construct new FM Index
#' \item \code{fm_index_find} Find given queries in FM Index
#' \item \code{fm_index_save} Save FM Index to disk
#' \item \code{fm_index_load} Load FM Index from disk
#' }
#'
#' @param strings Vector of strings to construct FM index from
#' @param query Vector of strings to find in FM index
#' @param case_sensitive Build case-sensitive index if TRUE
#' @param index Index created with [fm_index_construct()]
#' @param path Path where to load index from or save index to
#' @examples
#'
#' data("state")
#'
#' index <- fm_index_construct(state.name, case_sensitive = FALSE)
#' # Find all states with "new" in their names
#' hits <- fm_index_find("new", index)
#' hits
#' # Show matching strings in library
#' state.name[hits$library_index]
#'
#' hits <- fm_index_find("ar")
#' hits
#' state.name[hits$library_index]
#'
#' tmp_path <- tempfile()
#' fm_index_save(index, tmp_path)
#' index_2 <- fm_index_load(tmp_path)
#'
#' identical(
#'   fm_index_find("new", index),
#'   fm_index_find("new", index_2)
#' )
#'
#' @rdname fmindex
#' @export
#' @importFrom stringi stri_trans_tolower
fm_index_construct <- function(strings, case_sensitive = FALSE) {
    .Call(`_fm_index_fm_index_construct`, strings, case_sensitive)
}

#' @rdname fmindex
#' @export
fm_index_find <- function(query, index) {
    .Call(`_fm_index_fm_index_find`, query, index)
}

#' @rdname fmindex
#' @export
fm_index_save <- function(index, path) {
    invisible(.Call(`_fm_index_fm_index_save`, index, path))
}

#' @rdname fmindex
#' @export
fm_index_load <- function(path) {
    .Call(`_fm_index_fm_index_load`, path)
}

